export interface PagefindResult {
  url: string;
  excerpt: string;
  meta?: { title?: string };
}

export interface PagefindModule {
  init?: () => void;
  search: (q: string) => Promise<{ results: { data: () => Promise<PagefindResult> }[] }>;
}

// Loaded via the Function constructor so Vite never sees a static `import(...)`
// to analyze/preload-wrap — /pagefind/pagefind.js only exists after the
// production build (generated by the postbuild pagefind CLI step), so any
// build-time handling of this specifier is both impossible and undesired.
const dynamicImport = new Function('specifier', 'return import(specifier)') as (
  specifier: string,
) => Promise<PagefindModule>;

let pagefindPromise: Promise<PagefindModule | null> | null = null;

/** Lazily loads and initializes Pagefind, memoized for the lifetime of the
 * current page (every navigation here is a full page load, not a client
 * router, so this doesn't need to survive across pages). Resolves to null
 * in dev mode, where /pagefind/pagefind.js doesn't exist yet. */
export function getPagefind(): Promise<PagefindModule | null> {
  if (!pagefindPromise) {
    pagefindPromise = dynamicImport('/pagefind/pagefind.js')
      .then((mod) => {
        mod.init?.();
        return mod;
      })
      .catch(() => null);
  }
  return pagefindPromise;
}
